### ISSUE TITLE
Azure Cache for Redis taking more than 20 minutes everytime to get provisioned using Terraform

### ISSUE THREAD

**Issue by chetansir** [Azure/AzureCacheForRedis#6]
I am using Terraform's ARM provider to create multiple resources and Azure cache for Redis is taking a lot of time(minimum 20 minutes to get provisioned). This creates an issue for other resources to wait for getting picked for provisioning. Looks like an issue from Azure side as it takes around 10 minutes or so to get created via Azure CLI or portal as well. Please advise

**Comment by philon-msft** [comment]
Hi @chetansir 20+ minutes is a typical provisioning duration so it sounds like you're seeing normal behavior through Terraform. 10 minutes would be extremely fast, but may be possible depending on the SKU and configuration you specify. In general, we recommend long-lived cache instances rather than (re)creating them frequently.
